// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoyoRxHKf-NVRQmuxZJLvQ3ckk2rOXEYk',
    appId: '1:1030571024951:web:bff3e4c9dd0c2b019c15b2',
    messagingSenderId: '1030571024951',
    projectId: 'dream-25',
    authDomain: 'dream-25.firebaseapp.com',
    databaseURL: 'https://dream-25-default-rtdb.firebaseio.com',
    storageBucket: 'dream-25.appspot.com',
    measurementId: 'G-XHLYK8YQDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJVv9KH2gVJyRZtWIePOSGHYtk3s1-Y6o',
    appId: '1:1030571024951:android:91f611e5d6f0e5e79c15b2',
    messagingSenderId: '1030571024951',
    projectId: 'dream-25',
    databaseURL: 'https://dream-25-default-rtdb.firebaseio.com',
    storageBucket: 'dream-25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyxfVwKp77AzcTON-9OJcfXLxjRh5mz5Q',
    appId: '1:1030571024951:ios:c95ba024a30233ff9c15b2',
    messagingSenderId: '1030571024951',
    projectId: 'dream-25',
    databaseURL: 'https://dream-25-default-rtdb.firebaseio.com',
    storageBucket: 'dream-25.appspot.com',
    iosClientId: '1030571024951-g1suaj1mocod3cp1vl38blu85tvtqk0t.apps.googleusercontent.com',
    iosBundleId: 'com.dreamapp.drm25',
  );
}
